[env:custom_esp32]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = 
    ${arduino_base.build_flags}
    -D ARDUINO_ARCH_ESP32
    -D HAS_BLUETOOTH=1
    -D HAS_SCREEN=1
    -D USE_SH1106=0
    -D USE_SSD1306=1
    -D SCREEN_WIDTH=128
    -D SCREEN_HEIGHT=64
    -D HAS_GPS=1
    -D HAS_BUTTON=1
    -D LORA_SCK=5
    -D LORA_MISO=19
    -D LORA_MOSI=27
    -D LORA_CS=18
    -D LORA_RESET=14
    -D LORA_DIO0=26
lib_deps =
    ${arduino_base.lib_deps}
